name: Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version name'
        required: true
        default: '0.0.0'


jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check
        run: echo "Releas ...."